name: Build compiler executable
on: [push, pull_request]


jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3

      with:
        python-version: '3.10'

    - name: Install package
      run: pip install .

    - name: Test compiler help message
      run: cpq -h

    - name: Prepare pyinstaller
      run: pip install pyinstaller

    - name: Compile the compiler-launcher
      run: pyinstaller launcher.py --onefile --name cpq

    - name: Upload dist artifacts
      uses: actions/upload-artifact@v4

      with:
        name: compiler
        path: dist
